<?php
$ROUTES = [
    'initial' => [
        'id' => '000',
        'name' => '< Bitte eine Route auswählen >',
        'stations' => [
            ['id' => 'A', 'name' => 'Aadorf', 'abbr' => 'AAA', 'km' => 0],
            ['id' => 'B', 'name' => 'Bethal', 'abbr' => 'BBB', 'km' => 10],
        ]
    ],
    'locarnese' => [
        'id' => 'locarnese',
        'name' => 'Locarno',
        'stations' => [
            ['id' => 'GIU', 'name' => 'Giubiasco', 'abbr' => 'GIU', 'km' => 154.04],
            ['id' => 'SAN', 'name' => 'S. Antonino', 'abbr' => 'SAN', 'km' => 156.8],
            ['id' => 'CD', 'name' => 'Cadenazzo', 'abbr' => 'CD', 'km' => 159.48],
            ['id' => 'RIAZ', 'name' => 'Riazzino', 'abbr' => 'RIAZ', 'km' => 164.84],
            ['id' => 'GDA', 'name' => 'Gordola', 'abbr' => 'GDA', 'km' => 166.57],
            ['id' => 'TEN', 'name' => 'Tenero', 'abbr' => 'TEN', 'km' => 167.83],
            ['id' => 'MINU', 'name' => 'Minusio', 'abbr' => 'MINU', 'km' => 170.5],
            ['id' => 'LO', 'name' => 'Locarno', 'abbr' => 'LO', 'km' => 171.94],
        ]
    ],
    'lugano' => [
        'id' => 'lugano',
        'name' => 'Lugano',
        'stations' => [
            ['id' => 'RIB', 'name' => 'Rivera-Bironico', 'abbr' => 'RIB', 'km' => 165.21],
            ['id' => 'MEZ', 'name' => 'Mezzovico', 'abbr' => 'MEZ', 'km' => 168.86],
            ['id' => 'MEZS', 'name' => 'Sigirino', 'abbr' => 'MEZS', 'km' => 171.27],
            ['id' => 'TAV', 'name' => 'Taverne-Torricella', 'abbr' => 'TAV', 'km' => 173.99],
            ['id' => 'LAM', 'name' => 'Lamone-Cadempino', 'abbr' => 'LAM', 'km' => 176.1],
            ['id' => 'VEZB', 'name' => 'Vezia', 'abbr' => 'VEZB', 'km' => 178.02],
            ['id' => 'LG', 'name' => 'Lugano', 'abbr' => 'LG', 'km' => 180.45],
            ['id' => 'LGP', 'name' => 'Paradiso', 'abbr' => 'LGP', 'km' => 182.83],
            ['id' => 'MDE', 'name' => 'Melide', 'abbr' => 'MDE', 'km' => 187.23],
            ['id' => 'MAR', 'name' => 'Maroggia-Melano', 'abbr' => 'MAR', 'km' => 191.03]
        ]
    ],
    'ceneri-tunnel' => [
        'id' => 'ceneri-cbt',
        'name' => 'Ceneri',
        'stations' => [
            ['id' => 'SAN', 'name' => 'S. Antonino', 'abbr' => 'SAN', 'km' => 225],
            ['id' => 'CAMO', 'name' => 'Camorino', 'abbr' => 'CAMO', 'km' => 227.36],
            ['id' => 'VEZB', 'name' => 'Vezia', 'abbr' => 'VEZB', 'km' => 243.36],
            ['id' => 'LG', 'name' => 'Lugano', 'abbr' => 'LG', 'km' => 245.74],
        ]
    ],
    'airolo' => [
        'id' => 'airolo',
        'name' => 'Airolo',
        'stations' => [
            ['id' => 'GOE', 'name' => 'Göschenen', 'abbr' => 'GOE', 'km' => 70.45],
            ['id' => 'AI', 'name' => 'Airolo', 'abbr' => 'AI', 'km' => 86.2],
            ['id' => 'AP', 'name' => 'Ambri-Piotta', 'abbr' => 'AP', 'km' => 93.04],
            ['id' => 'RO', 'name' => 'Rodi-Fiesso', 'abbr' => 'RO', 'km' => 97.84],
            ['id' => 'PARD', 'name' => 'Pardorea', 'abbr' => 'PARD', 'km' => 101.93],
            ['id' => 'FA', 'name' => 'Faido', 'abbr' => 'FA', 'km' => 106],
            ['id' => 'BO', 'name' => 'Bodio', 'abbr' => 'BO', 'km' => 125.5],
        ]
    ],
    'giubiasco' => [
        'id' => 'giubiasco',
        'name' => 'Monte-Ceneri (Giubiasco)',
        'stations' => [
            ['id' => 'BEL', 'name' => 'Bellinzona', 'abbr' => 'BEL', 'km' => 150.9],
            ['id' => 'GIU', 'name' => 'Giubiasco', 'abbr' => 'GIU', 'km' => 154.0],
            ['id' => 'VIGA', 'name' => 'Vigana', 'abbr' => 'VIGA', 'km' => 158.01],
            ['id' => 'ALM', 'name' => 'Al Motto', 'abbr' => 'ALM', 'km' => 161.35],
            ['id' => 'RIB', 'name' => 'Rivera-Bironico', 'abbr' => 'RIB', 'km' => 165.21],
            ['id' => 'MEZ', 'name' => 'Mezzovico', 'abbr' => 'MEZ', 'km' => 168.86],
            ['id' => 'MEZS', 'name' => 'Mezzovico-Sigirino', 'abbr' => 'MEZS', 'km' => 171.27],
            ['id' => 'TAV', 'name' => 'Taverne-Torricella', 'abbr' => 'TAV', 'km' => 173.99],
            ['id' => 'LAM', 'name' => 'Lamone-Cadempino', 'abbr' => 'LAM', 'km' => 176.1],
            ['id' => 'VEZB', 'name' => 'Vezia', 'abbr' => 'VEZB', 'km' => 178.02],
            ['id' => 'LG', 'name' => 'Lugano', 'abbr' => 'LG', 'km' => 180.45],
        ]
    ],
    'ceneri-sud' => [
        'id' => 'ceneri-sud',
        'name' => 'Ceneri-Süd',
        'stations' => [
            ['id' => 'VEZB', 'name' => 'Vezia', 'abbr' => 'VEZB', 'km' => 178.02],
            ['id' => 'LG', 'name' => 'Lugano', 'abbr' => 'LG', 'km' => 180.4],
            ['id' => 'LGP', 'name' => 'Paradiso', 'abbr' => 'LGP', 'km' => 182.8],
            ['id' => 'MDE', 'name' => 'Melide', 'abbr' => 'MDE', 'km' => 187.2],
            ['id' => 'MAR', 'name' => 'Maroggia-Melano', 'abbr' => 'MAR', 'km' => 191],
            ['id' => 'CAP', 'name' => 'Capolago-Riva-S.Vitale', 'abbr' => 'CAP', 'km' => 194.6],
            ['id' => 'MOSM', 'name' => 'Mendrisio S. Martino', 'abbr' => 'MOSM', 'km' => 197.7],
            ['id' => 'MEN', 'name' => 'Mendrisio', 'abbr' => 'MEN', 'km' => 198.7],
            ['id' => 'BAL', 'name' => 'Balerna', 'abbr' => 'BAL', 'km' => 203.53],
            ['id' => 'CHI', 'name' => 'Chiasso', 'abbr' => 'CHI', 'km' => 206.17],
        ]
    ],
    'gotthard-sud' => [
        'id' => 'gotthard-sud',
        'name' => 'Gotthard Süd',
        'stations' => [
            ['id' => 'BEL', 'name' => 'Bellinzona', 'abbr' => 'BEL', 'km' => 150.9],
            ['id' => 'GIU', 'name' => 'Giubiasco', 'abbr' => 'GIU', 'km' => 154.0],
            ['id' => 'VIGA', 'name' => 'Vigana', 'abbr' => 'VIGA', 'km' => 158.01],
            ['id' => 'ALM', 'name' => 'Al Motto', 'abbr' => 'ALM', 'km' => 161.35],
            ['id' => 'RIB', 'name' => 'Rivera-Bironico', 'abbr' => 'RIB', 'km' => 165.21],
            ['id' => 'MEZ', 'name' => 'Mezzovico', 'abbr' => 'MEZ', 'km' => 168.86],
            ['id' => 'MEZS', 'name' => 'Mezzovico-Sigirino', 'abbr' => 'MEZS', 'km' => 171.27],
            ['id' => 'TAV', 'name' => 'Taverne-Torricella', 'abbr' => 'TAV', 'km' => 173.99],
            ['id' => 'LAM', 'name' => 'Lamone-Cadempino', 'abbr' => 'LAM', 'km' => 176.1],
            ['id' => 'VEZB', 'name' => 'Vezia', 'abbr' => 'VEZB', 'km' => 178.02],
            ['id' => 'LG', 'name' => 'Lugano', 'abbr' => 'LG', 'km' => 180.45],
            ['id' => 'LGP', 'name' => 'Paradiso', 'abbr' => 'LGP', 'km' => 182.83],
            ['id' => 'MDE', 'name' => 'Melide', 'abbr' => 'MDE', 'km' => 187.23],
            ['id' => 'MAR', 'name' => 'Maroggia-Melano', 'abbr' => 'MAR', 'km' => 191.03]
        ]
    ],
    'chi-cosg' => [
        'id' => 'chi-cosg',
        'name' => 'Chiasso-Como',
        'stations' => [
            ['id' => 'BAL', 'name' => 'BAL', 'abbr' => 'BAL', 'km' => 203.53],
            ['id' => 'CHI', 'name' => 'CHI', 'abbr' => 'CHI', 'km' => 206.17],
            ['id' => 'CHIE', 'name' => 'CHIE', 'abbr' => 'CHIE', 'km' => 206.46],
            ['id' => 'COSG', 'name' => 'COSG', 'abbr' => 'COSG', 'km' => 210],
            ['id' => 'CONC', 'name' => 'CONC', 'abbr' => 'CONC', 'km' => 213.5],
            ['id' => 'ALCA', 'name' => 'ALCA', 'abbr' => 'ALCA', 'km' => 215],
        ]
    ],
    'acla-micl' => [
        'id' => 'milano',
        'name' => 'Milano-Como',
        'stations' => [
            ['id' => 'ALCA', 'name' => 'ALCA', 'abbr' => 'ALCA', 'km' => 215],
            ['id' => 'BIRO', 'name' => 'BIRO', 'abbr' => 'BIRO', 'km' => 216.279],
            ['id' => 'CUCC', 'name' => 'CUCC', 'abbr' => 'CUCC', 'km' => 219.6],
            ['id' => 'CACE', 'name' => 'CACE', 'abbr' => 'CACE', 'km' => 222.764],
            ['id' => 'CARI', 'name' => 'CARI', 'abbr' => 'CARI', 'km' => 225.17],
            ['id' => 'CALE', 'name' => 'CALE', 'abbr' => 'CALE', 'km' => 229.84],
            ['id' => 'SESO', 'name' => 'SESO', 'abbr' => 'SESO', 'km' => 232],
            ['id' => 'SER', 'name' => 'SER', 'abbr' => 'SER', 'km' => 235.337],
            ['id' => 'DESI', 'name' => 'DESI', 'abbr' => 'DESI', 'km' => 238.5],
            ['id' => 'LIMU', 'name' => 'LIMU', 'abbr' => 'LIMU', 'km' => 240.58],
            ['id' => 'MOZ', 'name' => 'MOZ', 'abbr' => 'MOZ', 'km' => 245],
            ['id' => 'SESG', 'name' => 'SESG', 'abbr' => 'SESG', 'km' => 249.8],
            ['id' => 'MIGP', 'name' => 'MIGP', 'abbr' => 'MIGP', 'km' => 253.5],
            ['id' => 'MICL', 'name' => 'MICL', 'abbr' => 'MICL', 'km' => 256.851],
        ]
    ],
    'asm-w' => [
        'id' => 'asm-w',
        'name' => 'ASM-W',
        'stations' => [
            ['id' => 'SOAS', 'name' => 'Solothurn', 'abbr' => 'SOAS', 'km' => 0],
            ['id' => 'SOBT', 'name' => 'Baseltor', 'abbr' => 'SOBT', 'km' => 0.8],
            ['id' => 'SOST', 'name' => 'Sternen', 'abbr' => 'SOST', 'km' => 1.13],
            ['id' => 'STKA', 'name' => 'St. Katharinen', 'abbr' => 'STKA', 'km' => 1.75],
            ['id' => 'FEBR', 'name' => 'Feldbrunnen', 'abbr' => 'FEBR', 'km' => 2.35],
            ['id' => 'BDWE', 'name' => 'Bei den Weihern', 'abbr' => 'BDWE', 'km' => 3.62],
            ['id' => 'RIHO', 'name' => 'Riedholz', 'abbr' => 'RIHO', 'km' => 4.18],
            ['id' => 'FLUM', 'name' => 'Flumenthal', 'abbr' => 'FLUM', 'km' => 6.23],
            ['id' => 'SIGG', 'name' => 'Siggeren', 'abbr' => 'SIGG', 'km' => 7],
            ['id' => 'ATTI', 'name' => 'Attiswil', 'abbr' => 'ATTI', 'km' => 7.76],
            ['id' => 'W', 'name' => 'Wende', 'abbr' => 'W', 'km' => 10],
            ['id' => 'WIED', 'name' => 'Widsbach', 'abbr' => 'WIED', 'km' => 10.32],
            ['id' => 'OBBI', 'name' => 'Oberbipp', 'abbr' => 'OBBI', 'km' => 11.71],
            ['id' => 'OPIN', 'name' => 'Oberbipp Industrie', 'abbr' => 'OPIN', 'km' => 12.405],
            ['id' => 'BULI', 'name' => 'Buchli', 'abbr' => 'BULI', 'km' => 13.1],
            ['id' => 'NB A', 'name' => 'Unbekannt', 'abbr' => 'NB A', 'km' => 14.54],
            ['id' => 'NIIN A', 'name' => 'Niederbipp Industrie', 'abbr' => 'NIIN', 'km' => 15.5],
            ['id' => 'OEEN', 'name' => 'Oensingen', 'abbr' => 'OEEN', 'km' => 17],
        ]
    ],
    'asm-a' => [
        'id' => 'asm-a',
        'name' => 'ASM-A',
        'stations' => [
            ['id' => 'OEEN', 'name' => 'Oensingen', 'abbr' => 'OEEN', 'km' => 17],
            ['id' => 'NIIN B', 'name' => 'Niederbipp Industrie', 'abbr' => 'NIIN', 'km' => 18.5],
            ['id' => 'NB B', 'name' => 'Niederbipp', 'abbr' => 'NB B', 'km' => 19.8],
            ['id' => 'NBD', 'name' => 'Niederbipp Dorf', 'abbr' => 'NBD', 'km' => 20.19],
            ['id' => 'SNAG', 'name' => 'Scharnageln', 'abbr' => 'SNAG', 'km' => 20.78],
            ['id' => 'HZH', 'name' => 'Houzhüsli', 'abbr' => 'HZH', 'km' => 21.74],
            ['id' => 'BAN', 'name' => 'Bannwil', 'abbr' => 'BAN', 'km' => 24.61],
            ['id' => 'AARS', 'name' => 'Aarwangen Schloss', 'abbr' => 'AARS', 'km' => 26.54],
            ['id' => 'AARW', 'name' => 'Aarwangen', 'abbr' => 'AARW', 'km' => 27.33],
            ['id' => 'AARV', 'name' => 'Vorstadt', 'abbr' => 'AARV', 'km' => 27.77],
            ['id' => 'HAMU', 'name' => 'Hard-Mumenthl', 'abbr' => 'HAMU', 'km' => 28.09],
            ['id' => 'LTHG', 'name' => 'Gaswerk', 'abbr' => 'LTHG', 'km' => 29.43],
            ['id' => 'LTHAA', 'name' => 'Langenthal', 'abbr' => 'LTHAA', 'km' => 30.53],
        ]
    ],
    'asm-r' => [
        'id' => 'asm-r',
        'name' => 'ASM-R',
        'stations' => [
            ['id' => 'LTHAA', 'name' => 'Langenthal', 'abbr' => 'LTHAA', 'km' => 30.53],
            ['id' => 'LTHG', 'name' => 'Gaswerk', 'abbr' => 'LTHG', 'km' => 31.43],
            ['id' => 'LTIN', 'name' => 'Industrie Nord', 'abbr' => 'LTIN', 'km' => 32.31],
            ['id' => 'KAHE', 'name' => 'Kaltenherberg', 'abbr' => 'KAHE', 'km' => 33.57],
            ['id' => 'ROSC', 'name' => 'Schmitten', 'abbr' => 'ROSC', 'km' => 34.83],
            ['id' => 'ROGD', 'name' => 'Roggwil Dorf', 'abbr' => 'ROGD', 'km' => 35.43],
            ['id' => 'ROBU', 'name' => 'Buchägerten', 'abbr' => 'ROBU', 'km' => 36.29],
            ['id' => 'SURB', 'name' => 'St. Urban', 'abbr' => 'SURB', 'km' => 36.86],
            ['id' => 'ZIE', 'name' => 'Zieglei', 'abbr' => 'ZIE', 'km' => 37.37],
        ]
    ],
    'btb' => [
        'id' => 'btb',
        'name' => 'Emmental',
        'stations' => [
            ['id' => 'BDF', 'name' => 'Burgdorf', 'abbr' => 'BDF', 'km' => -6.93],
            ['id' => 'BDFS', 'name' => 'Steinhof', 'abbr' => 'BDFS', 'km' => -5.03],
            ['id' => 'OBB', 'name' => 'Oberburg', 'abbr' => 'OBB', 'km' => -3.37],
            ['id' => 'HA', 'name' => 'Hasle-Rüegsau', 'abbr' => 'HA', 'km' => 0],
            ['id' => 'SHIE', 'name' => 'Schafhausen i.E.', 'abbr' => 'SHIE', 'km' => 2.56],
            ['id' => 'BIGE', 'name' => 'Bigenthal', 'abbr' => 'BIGE', 'km' => 6.83],
            ['id' => 'WALK', 'name' => 'Walkringen', 'abbr' => 'WALK', 'km' => 8.89],
            ['id' => 'BIG', 'name' => 'Biglen', 'abbr' => 'BIG', 'km' => 12.09],
            ['id' => 'GH', 'name' => 'Grosshöchstetten', 'abbr' => 'GH', 'km' => 14.67],
            ['id' => 'KF', 'name' => 'Konolfingen', 'abbr' => 'KF', 'km' => 18.74],
            ['id' => 'STAL', 'name' => 'Stalden i.E.', 'abbr' => 'STAL', 'km' => 19.96],
            ['id' => 'OD', 'name' => 'Oberdiessbach', 'abbr' => 'OD', 'km' => 23.65],
            ['id' => 'BK', 'name' => 'Brenzikofen', 'abbr' => 'BK', 'km' => 26.08],
            ['id' => 'HMB', 'name' => 'Heimberg', 'abbr' => 'HMB', 'km' => 29.38],
        ]
    ],
    'rm' => [
        'id' => 'rm',
        'name' => 'Huttwil RM',
        'stations' => [
            ['id' => 'LTH', 'name' => 'Langenthal', 'abbr' => 'LTH', 'km' => 0],
            ['id' => 'LTHS', 'name' => 'Langenthal Süd', 'abbr' => 'LTHS', 'km' => 1.62],
            ['id' => 'LOTZ', 'name' => 'Lotzwil', 'abbr' => 'LOTZ', 'km' => 3.42],
            ['id' => 'GUBU', 'name' => 'Gutenburg', 'abbr' => 'GUBU', 'km' => 4.39],
            ['id' => 'MADI', 'name' => 'Madiswil', 'abbr' => 'MADI', 'km' => 6.04],
            ['id' => 'LHO', 'name' => 'Lindenholz', 'abbr' => 'LHO', 'km' => 7.52],
            ['id' => 'KDI', 'name' => 'Kleindietwil', 'abbr' => 'KDI', 'km' => 8.44],
            ['id' => 'RBA', 'name' => 'Rohrbach', 'abbr' => 'RBA', 'km' => 10.54],
            ['id' => 'HWIL', 'name' => 'Huttwil', 'abbr' => 'HWIL', 'km' => 14.09],
			['id' => 'GOND', 'name' => 'Gondiswil', 'abbr' => 'GOND', 'km' => 18.03],
			['id' => 'HUEW', 'name' => 'Hüswil West', 'abbr' => 'HUEW', 'km' => 19],
			['id' => 'HUE', 'name' => 'Hüswil', 'abbr' => 'HUE', 'km' => 19.81],
			['id' => 'ZELL', 'name' => 'ZELL', 'abbr' => 'ZELL', 'km' => 21.69],
			['id' => 'GET', 'name' => 'Gettnau', 'abbr' => 'GET', 'km' => 25.17],
			['id' => 'GETG', 'name' => 'Makies', 'abbr' => 'GETG', 'km' => 26.3],
			['id' => 'WSAU', 'name' => 'Willisau', 'abbr' => 'WSAU', 'km' => 28.75],
			['id' => 'MAUW', 'name' => 'Kronospan', 'abbr' => 'MAUW', 'km' => 33.66],
			['id' => 'MAU', 'name' => 'Menznau', 'abbr' => 'MAU', 'km' => 34.68],
			['id' => 'WHW', 'name' => 'Weid', 'abbr' => 'WHW', 'km' => 37.71],
			['id' => 'WH', 'name' => 'Wolhusen', 'abbr' => 'WH', 'km' => 39.32],
        ]
    ],
    'Langetental' => [
        'id' => 'Langetental',
        'name' => 'Langetental',
        'stations' => [
            ['id' => 'LTH', 'name' => 'Langenthal', 'abbr' => 'LTH', 'km' => 0],
            ['id' => 'LTHS', 'name' => 'Langenthal Süd', 'abbr' => 'LTHS', 'km' => 1.62],
            ['id' => 'LOTZ', 'name' => 'Lotzwil', 'abbr' => 'LOTZ', 'km' => 3.42],
            ['id' => 'GUBU', 'name' => 'Gutenburg', 'abbr' => 'GUBU', 'km' => 4.39],
            ['id' => 'MADI', 'name' => 'Madiswil', 'abbr' => 'MADI', 'km' => 6.04],
            ['id' => 'LHO', 'name' => 'Lindenholz', 'abbr' => 'LHO', 'km' => 7.52],
            ['id' => 'KDI', 'name' => 'Kleindietwil', 'abbr' => 'KDI', 'km' => 8.44],
            ['id' => 'RBA', 'name' => 'Rohrbach', 'abbr' => 'RBA', 'km' => 10.54],
            ['id' => 'HWIL', 'name' => 'Huttwil', 'abbr' => 'HWIL', 'km' => 14.09],
        ]
    ],
    'vhb' => [
        'id' => 'vhb',
        'name' => 'Huttwi VHB',
        'stations' => [
            ['id' => 'RBA', 'name' => 'Rohrbach', 'abbr' => 'RBA', 'km' => 10.54],
            ['id' => 'HWIL', 'name' => 'Huttwil', 'abbr' => 'HWIL', 'km' => 14.09],
			['id' => 'GOND', 'name' => 'Gondiswil', 'abbr' => 'GOND', 'km' => 18.03],
			['id' => 'HUEW', 'name' => 'Hüswil West', 'abbr' => 'HUEW', 'km' => 19],
			['id' => 'HUE', 'name' => 'Hüswil', 'abbr' => 'HUE', 'km' => 19.81],
			['id' => 'ZELL', 'name' => 'ZELL', 'abbr' => 'ZELL', 'km' => 21.69],
			['id' => 'GET', 'name' => 'Gettnau', 'abbr' => 'GET', 'km' => 25.17],
			['id' => 'GETG', 'name' => 'Makies', 'abbr' => 'GETG', 'km' => 26.3],
			['id' => 'WSAU', 'name' => 'Willisau', 'abbr' => 'WSAU', 'km' => 28.75],
			['id' => 'MAUW', 'name' => 'Kronospan', 'abbr' => 'MAUW', 'km' => 33.66],
			['id' => 'MAU', 'name' => 'Menznau', 'abbr' => 'MAU', 'km' => 34.68],
			['id' => 'WHW', 'name' => 'Weid', 'abbr' => 'WHW', 'km' => 37.71],
			['id' => 'WH', 'name' => 'Wolhusen', 'abbr' => 'WH', 'km' => 39.32],
        ]
	],
    'thun-aare' => [
        'id' => 'thun-aare',
        'name' => 'Thun (SBB)',
        'stations' => [
            ['id' => 'KI', 'name' => 'Kiesen', 'abbr' => 'KI', 'km' => 25.1],
            ['id' => 'UTI', 'name' => 'Uttigen', 'abbr' => 'UTI', 'km' => 27.9],
            ['id' => 'LNF', 'name' => 'Lerchenfeld', 'abbr' => 'LNF', 'km' => 30.9],
            ['id' => 'TH', 'name' => 'Thun', 'abbr' => 'TH', 'km' => 33.82],
			['id' => 'THSC', 'name' => 'Schadau', 'abbr' => 'THSC', 'km' => 34.39],
			['id' => 'THDA', 'name' => 'Dürrenast', 'abbr' => 'THDA', 'km' => 35.96],
            ['id' => 'GW', 'name' => 'Gwatt', 'abbr' => 'GW', 'km' => 37.49],
            ['id' => 'EIN', 'name' => 'Einigen', 'abbr' => 'EIN', 'km' => 39.79],
			['id' => 'SPMN', 'name' => 'Spiezmoos Nord', 'abbr' => 'SPMN', 'km' => 42.59],
			['id' => 'SP', 'name' => 'Spiez', 'abbr' => 'SP', 'km' => 44.09],
        ]
    ],
    'thun-etb' => [
        'id' => 'thun-etb',
        'name' => 'Thun (BLS-B)',
        'stations' => [
            ['id' => 'OD', 'name' => 'Oberdiessbach', 'abbr' => 'OD', 'km' => 23.65],
			['id' => 'BK', 'name' => 'Brenzikofen', 'abbr' => 'BK', 'km' => 26.08],
			['id' => 'HMB', 'name' => 'Heimberg', 'abbr' => 'HMB', 'km' => 29.38],
            ['id' => 'LAED', 'name' => 'Lädeli', 'abbr' => 'LAED', 'km' => 30.25],
            ['id' => 'STEF', 'name' => 'Steffisburg', 'abbr' => 'STEF', 'km' => 31.51],
            ['id' => 'SWB', 'name' => 'Schwäbis', 'abbr' => 'SWB', 'km' => 32.73],
            ['id' => 'TH', 'name' => 'Thun', 'abbr' => 'TH', 'km' => 33.82],
			['id' => 'THSC', 'name' => 'Schadau', 'abbr' => 'THSC', 'km' => 34.39],
			['id' => 'THDA', 'name' => 'Dürrenast', 'abbr' => 'THDA', 'km' => 35.96],
            ['id' => 'GW', 'name' => 'Gwatt', 'abbr' => 'GW', 'km' => 37.49],
            ['id' => 'EIN', 'name' => 'Einigen', 'abbr' => 'EIN', 'km' => 39.79],
			['id' => 'SPMN', 'name' => 'Spiezmoos Nord', 'abbr' => 'SPMN', 'km' => 42.59],
			['id' => 'SP', 'name' => 'Spiez', 'abbr' => 'SP', 'km' => 44.09],
        ]
    ],
    'thunersee-see' => [
        'id' => 'thunersee-see',
        'name' => 'Thunersee (See)',
        'stations' => [
            ['id' => 'EIN', 'name' => 'Einigen', 'abbr' => 'EIN', 'km' => 5.4],
            ['id' => 'SPMN', 'name' => 'Spiezmoos Nord', 'abbr' => 'SPMN', 'km' => 8.2],
            ['id' => 'SP', 'name' => 'Spiez', 'abbr' => 'SP', 'km' => 9.7],
            ['id' => 'SPO', 'name' => 'Spiez Ost', 'abbr' => 'SPO', 'km' => 11.6],
            ['id' => 'FS', 'name' => 'Faulesee', 'abbr' => 'FS', 'km' => 11.8],
            ['id' => 'KH', 'name' => 'Krattighalde', 'abbr' => 'KH', 'km' => 15.3],
            ['id' => 'LBAD', 'name' => 'Leissigbad', 'abbr' => 'LBAD', 'km' => 16.7],
            ['id' => 'LSS', 'name' => 'Leissigen', 'abbr' => 'LSS', 'km' => 18.5],
            ['id' => 'DAE', 'name' => 'Därligen', 'abbr' => 'DAE', 'km' => 22],
            ['id' => 'IW', 'name' => 'Interlaken West', 'abbr' => 'IW', 'km' => 26],
            ['id' => 'IO', 'name' => 'Interlaken Ost', 'abbr' => 'IO', 'km' => 28],
            ['id' => 'BOWE', 'name' => 'Bönigen Werkstätte BLS', 'abbr' => 'BOWE', 'km' => 29.5],
            ['id' => 'BOGE', 'name' => 'Lütschinenbrücke', 'abbr' => 'BOGE', 'km' => 29.6],
            ['id' => 'BOEN', 'name' => 'Bönigen', 'abbr' => 'BOEN', 'km' => 30.2],
        ]
    ],
    'kandersteg' => [
        'id' => 'kandersteg',
        'name' => 'Lötschen-Nord',
        'stations' => [
            ['id' => 'SP', 'name' => 'Spiez', 'abbr' => 'SP', 'km' => -0.11],
			['id' => 'HEU', 'name' => 'Heustrich-Emdtal', 'abbr' => 'HEU', 'km' => 5.16],
			['id' => 'MUE', 'name' => 'Mülenen', 'abbr' => 'MUE', 'km' => 6.85],
            ['id' => 'REIK', 'name' => 'Reichenbach i.K.', 'abbr' => 'REIK', 'km' => 8.29],
            ['id' => 'WENE', 'name' => 'Wengi-Ey', 'abbr' => 'WENE', 'km' => 10.28],
            ['id' => 'FR', 'name' => 'Frutigen', 'abbr' => 'FR', 'km' => 13.54],
			['id' => 'FRNP', 'name' => 'Frutigen LBT', 'abbr' => 'FRNP', 'km' => 14],
            ['id' => 'KG', 'name' => 'Kandergrund', 'abbr' => 'KG', 'km' => 17.45],
            ['id' => 'BL', 'name' => 'Blausee-Mitholz', 'abbr' => 'BL', 'km' => 22.35],
            ['id' => 'FEB', 'name' => 'Felsenburg', 'abbr' => 'FEB', 'km' => 27.11],
            ['id' => 'KA', 'name' => 'Kandersteg', 'abbr' => 'KA', 'km' => 31.57],
			['id' => 'EGGE', 'name' => 'Eggenschwand', 'abbr' => 'EGGE', 'km' => 33.1],
			['id' => 'TS', 'name' => 'Tunnelstation', 'abbr' => 'TS', 'km' => 40.01],
            ['id' => 'GOSW', 'name' => 'Goppenstein Lötschberg', 'abbr' => 'GOSW', 'km' => 47.08],
			['id' => 'GO', 'name' => 'Goppenstein', 'abbr' => 'GO', 'km' => 48.44],
        ]
    ],
    'frutigen' => [
        'id' => 'frutigen',
        'name' => 'Frutigen LBT',
        'stations' => [
            ['id' => 'SP', 'name' => 'Spiez', 'abbr' => 'SP', 'km' => -0.11],
			['id' => 'HEU', 'name' => 'Heustrich-Emdtal', 'abbr' => 'HEU', 'km' => 5.16],
			['id' => 'MUE', 'name' => 'Mülenen', 'abbr' => 'MUE', 'km' => 6.85],
            ['id' => 'REIK', 'name' => 'Reichenbach i.K.', 'abbr' => 'REIK', 'km' => 8.29],
            ['id' => 'WENE', 'name' => 'Wengi-Ey', 'abbr' => 'WENE', 'km' => 10.28],
            ['id' => 'FR', 'name' => 'Frutigen', 'abbr' => 'FR', 'km' => 13.54],
			['id' => 'ADL', 'name' => 'Adelrain', 'abbr' => 'ADL', 'km' => 15],
			['id' => 'MITH', 'name' => 'Mitholz', 'abbr' => 'MITH', 'km' => 22.02],
			['id' => 'FERD', 'name' => 'Ferden', 'abbr' => 'FERD', 'km' => 35.22],
			['id' => 'LOET', 'name' => 'Lötschen', 'abbr' => 'LOET', 'km' => 43.84],
			['id' => 'STGE', 'name' => 'St. German', 'abbr' => 'STGE', 'km' => 50.12],
			['id' => 'VI', 'name' => 'Visp', 'abbr' => 'VI', 'km' => 53.38],
        ]
    ],
    'goppenstein' => [
        'id' => 'goppenstein',
        'name' => 'Lötschen-Süd',
        'stations' => [
            ['id' => 'KA', 'name' => 'Kandersteg', 'abbr' => 'KA', 'km' => 31.57],
			['id' => 'EGGE', 'name' => 'Eggenschwand', 'abbr' => 'EGGE', 'km' => 33.1],
			['id' => 'TS', 'name' => 'Tunnelstation', 'abbr' => 'TS', 'km' => 40.01],
            ['id' => 'GOSW', 'name' => 'Goppenstein Lötschberg', 'abbr' => 'GOSW', 'km' => 47.08],
			['id' => 'GO', 'name' => 'Goppenstein', 'abbr' => 'GO', 'km' => 48.44],
			['id' => 'STOG', 'name' => 'Stockgraben', 'abbr' => 'STOG', 'km' => 49.47],
			['id' => 'HT', 'name' => 'Hohtenn', 'abbr' => 'HT', 'km' => 54.19],
			['id' => 'RARK', 'name' => 'Rarnerkumme', 'abbr' => 'RARK', 'km' => 57.29],
			['id' => 'AB', 'name' => 'Ausserberg', 'abbr' => 'AB', 'km' => 61.28],
			['id' => 'VIKT', 'name' => 'Viktoria', 'abbr' => 'VIKT', 'km' => 63.45],
			['id' => 'EB', 'name' => 'Eggerberg', 'abbr' => 'EB', 'km' => 64.88],
			['id' => 'LL', 'name' => 'Lalden', 'abbr' => 'LL', 'km' => 67.29],
			['id' => 'MUND', 'name' => 'Mundbach', 'abbr' => 'MUND', 'km' => 70.35],
			['id' => 'BR', 'name' => 'Brig', 'abbr' => 'BR', 'km' => 73.82],
        ]
    ],
    'frick' => [
        'id' => 'frick',
        'name' => 'Bözberg',
        'stations' => [
            ['id' => 'PR', 'name' => 'Pratteln', 'abbr' => 'PR', 'km' => -80.1],
            ['id' => 'KAU', 'name' => 'Kaiseraugst', 'abbr' => 'KAU', 'km' => -76.9],
            ['id' => 'RFAU', 'name' => 'Augarten', 'abbr' => 'RFAU', 'km' => -73.58],
            ['id' => 'RF', 'name' => 'Rheinfelden', 'abbr' => 'RF', 'km' => -71.63],
            ['id' => 'MOE', 'name' => 'Möhlin', 'abbr' => 'MOE', 'km' => -68.27],
            ['id' => 'MPF', 'name' => 'Mumpf', 'abbr' => 'MPF', 'km' => -61.88],
            ['id' => 'STS', 'name' => 'Stein-Säckingen', 'abbr' => 'STS', 'km' => -58.76],
            ['id' => 'EK', 'name' => 'Eiken', 'abbr' => 'EK', 'km' => -55.41],
            ['id' => 'FCK', 'name' => 'Frick', 'abbr' => 'FCK', 'km' => -51.85],
            ['id' => 'HNS', 'name' => 'Hornussen', 'abbr' => 'HNS', 'km' => -46.97],
            ['id' => 'EFG', 'name' => 'Effingen', 'abbr' => 'EFG', 'km' => -42.44],
            ['id' => 'SDO', 'name' => 'Schinznach Dorf', 'abbr' => 'SDO', 'km' => -39.2],
            ['id' => 'VIL', 'name' => 'Villnachern', 'abbr' => 'VIL', 'km' => -35.9],
            ['id' => 'BGN', 'name' => 'Brugg Nord', 'abbr' => 'BGN', 'km' => -32.4],
            ['id' => 'BG VL', 'name' => 'Brugg VL', 'abbr' => 'BG VL', 'km' => -31.8],
            ['id' => 'BG', 'name' => 'Brugg', 'abbr' => 'BG', 'km' => -31.2],
        ]
    ],
    'basel-rf' => [
        'id' => 'bs-rf',
        'name' => 'Basel – Rheinfelden',
        'stations' => [
            ['id' => 'BS', 'name' => 'BS', 'abbr' => 'BS', 'km' => 0],
            ['id' => 'BNO', 'name' => 'BNO', 'abbr' => 'BNO', 'km' => 10],
            ['id' => 'BSJS', 'name' => 'BSJS', 'abbr' => 'BSJS', 'km' => 20],
            ['id' => 'MU', 'name' => 'MU', 'abbr' => 'MU', 'km' => 30],
            ['id' => 'MUO', 'name' => 'MUO', 'abbr' => 'MUO', 'km' => 40],
            ['id' => 'PR', 'name' => 'PR', 'abbr' => 'PR', 'km' => 50],
            ['id' => 'PRSR', 'name' => 'PRSR', 'abbr' => 'PRSR', 'km' => 60],
            ['id' => 'KAU', 'name' => 'KAU', 'abbr' => 'KAU', 'km' => 70],
            ['id' => 'RFAU', 'name' => 'RFAU', 'abbr' => 'RFAU', 'km' => 80],
            ['id' => 'RF', 'name' => 'RF', 'abbr' => 'RF', 'km' => 90],
        ]
    ],
    'bözberg-lfg' => [
        'id' => 'bözberg-lfg',
        'name' => 'Laufenburg',
        'stations' => [
            ['id' => 'BS', 'name' => 'BS', 'abbr' => 'BS', 'km' => 0],
            ['id' => 'BNO', 'name' => 'BNO', 'abbr' => 'BNO', 'km' => 10],
            ['id' => 'BSJS', 'name' => 'BSJS', 'abbr' => 'BSJS', 'km' => 20],
            ['id' => 'MU', 'name' => 'MU', 'abbr' => 'MU', 'km' => 30],
            ['id' => 'MUO', 'name' => 'MUO', 'abbr' => 'MUO', 'km' => 40],
            ['id' => 'PR', 'name' => 'PR', 'abbr' => 'PR', 'km' => 50],
            ['id' => 'PRSR', 'name' => 'PRSR', 'abbr' => 'PRSR', 'km' => 60],
            ['id' => 'KAU', 'name' => 'KAU', 'abbr' => 'KAU', 'km' => 70],
            ['id' => 'RFAU', 'name' => 'RFAU', 'abbr' => 'RFAU', 'km' => 80],
            ['id' => 'RF', 'name' => 'RF', 'abbr' => 'RF', 'km' => 90],
            ['id' => 'MOE', 'name' => 'MOE', 'abbr' => 'MOE', 'km' => 100],
            ['id' => 'DOSS', 'name' => 'DOSS', 'abbr' => 'DOSS', 'km' => 110],
            ['id' => 'MPF', 'name' => 'MPF', 'abbr' => 'MPF', 'km' => 120],
            ['id' => 'STS', 'name' => 'STS', 'abbr' => 'STS', 'km' => 130],
            ['id' => 'SLN', 'name' => 'SLN', 'abbr' => 'SLN', 'km' => 140],
            ['id' => 'LFG', 'name' => 'LFG', 'abbr' => 'LFG', 'km' => 150],
            ['id' => 'SZ', 'name' => 'SZ', 'abbr' => 'SZ', 'km' => 160],
            ['id' => 'EZG', 'name' => 'EZG', 'abbr' => 'EZG', 'km' => 180],
            ['id' => 'SCWA', 'name' => 'SCWA', 'abbr' => 'SCWA', 'km' => 190],
            ['id' => 'LEI', 'name' => 'LEI', 'abbr' => 'LEI', 'km' => 200],
            ['id' => 'FU', 'name' => 'FU', 'abbr' => 'FU', 'km' => 210],
            ['id' => 'FE', 'name' => 'FE', 'abbr' => 'FE', 'km' => 220],
            ['id' => 'Koblenz', 'name' => 'KBFE', 'abbr' => 'Koblenz', 'km' => 230],
            ['id' => 'KB', 'name' => 'KB', 'abbr' => 'KB', 'km' => 240],
            ['id' => 'KBD', 'name' => 'KBD', 'abbr' => 'KBD', 'km' => 250],
            ['id' => 'RIET', 'name' => 'RIET', 'abbr' => 'RIET', 'km' => 260],
            ['id' => 'ZZ', 'name' => 'ZZ', 'abbr' => 'ZZ', 'km' => 270],
            ['id' => 'REK', 'name' => 'REK', 'abbr' => 'REK', 'km' => 290],
            ['id' => 'MELN', 'name' => 'MELN', 'abbr' => 'MELN', 'km' => 300],
            ['id' => 'RUEN', 'name' => 'RUEN', 'abbr' => 'RUEN', 'km' => 310],
            ['id' => 'KAAG', 'name' => 'KAAG', 'abbr' => 'KAAG', 'km' => 320],
            ['id' => 'WK', 'name' => 'WK', 'abbr' => 'WK', 'km' => 330],
            ['id' => 'ZWD', 'name' => 'ZWD', 'abbr' => 'ZWD', 'km' => 340],
            ['id' => 'EGL', 'name' => 'EGL', 'abbr' => 'EGL', 'km' => 350],
            ['id' => 'GF', 'name' => 'GF', 'abbr' => 'GF', 'km' => 360],
            ['id' => 'BUE', 'name' => 'BUE', 'abbr' => 'BUE', 'km' => 370],
            ['id' => 'EMB', 'name' => 'EMB', 'abbr' => 'EMB', 'km' => 380],
            ['id' => 'PFU', 'name' => 'PFU', 'abbr' => 'PFU', 'km' => 390],
            ['id' => 'WWUE', 'name' => 'WWUE', 'abbr' => 'WWUE', 'km' => 400],
            ['id' => 'WTOE', 'name' => 'WTOE', 'abbr' => 'WTOE', 'km' => 410],
        ]
    ],
    'lfg-koblenz' => [
        'id' => 'lfg-koblenz',
        'name' => 'Laufenburg Rhein',
        'stations' => [
            ['id' => 'MOE', 'name' => 'MOE', 'abbr' => 'MOE', 'km' => 100],
            ['id' => 'DOSS', 'name' => 'DOSS', 'abbr' => 'DOSS', 'km' => 110],
            ['id' => 'MPF', 'name' => 'MPF', 'abbr' => 'MPF', 'km' => 120],
            ['id' => 'STS', 'name' => 'STS', 'abbr' => 'STS', 'km' => 130],
            ['id' => 'SLN', 'name' => 'SLN', 'abbr' => 'SLN', 'km' => 140],
            ['id' => 'LFG', 'name' => 'LFG', 'abbr' => 'LFG', 'km' => 150],
            ['id' => 'SZ', 'name' => 'SZ', 'abbr' => 'SZ', 'km' => 160],
            ['id' => 'EZG', 'name' => 'EZG', 'abbr' => 'EZG', 'km' => 180],
            ['id' => 'SCWA', 'name' => 'SCWA', 'abbr' => 'SCWA', 'km' => 190],
            ['id' => 'LEI', 'name' => 'LEI', 'abbr' => 'LEI', 'km' => 200],
            ['id' => 'FU', 'name' => 'FU', 'abbr' => 'FU', 'km' => 210],
            ['id' => 'FE', 'name' => 'FE', 'abbr' => 'FE', 'km' => 220],
            ['id' => 'Koblenz', 'name' => 'KBFE', 'abbr' => 'Koblenz', 'km' => 230],
            ['id' => 'KB', 'name' => 'KB', 'abbr' => 'KB', 'km' => 240],
            ['id' => 'KBD', 'name' => 'KBD', 'abbr' => 'KBD', 'km' => 250],
            ['id' => 'RIET', 'name' => 'RIET', 'abbr' => 'RIET', 'km' => 260],
            ['id' => 'ZZ', 'name' => 'ZZ', 'abbr' => 'ZZ', 'km' => 270],
        ]
    ],
    'seebahn' => [
        'id' => 'seebahn',
        'name' => 'Seebahn (Kilchberg)',
        'stations' => [
            ['id' => 'ZUE', 'name' => 'Zürich HB', 'abbr' => 'ZUE', 'km' => 0.34],
            ['id' => 'ZWIE', 'name' => 'Wiedikon', 'abbr' => 'ZWIE', 'km' => 2.93],
            ['id' => 'ZEN', 'name' => 'Enge', 'abbr' => 'ZEN', 'km' => 3.93],
            ['id' => 'ZWOL', 'name' => 'Wollishofen', 'abbr' => 'ZWOL', 'km' => 5.81],
            ['id' => 'KIL', 'name' => 'Kilchberg', 'abbr' => 'KIL', 'km' => 8.86],
            ['id' => 'RUES', 'name' => 'Rüschlikon', 'abbr' => 'RUES', 'km' => 10.64],
        ]
    ],
    'zimmerberg' => [
        'id' => 'zimmerberg',
        'name' => 'Zimmerberg',
        'stations' => [
            ['id' => 'ZUE', 'name' => 'Zürich HB', 'abbr' => 'ZUE', 'km' => 0.34],
            ['id' => 'ZAU', 'name' => 'Aussersihl', 'abbr' => 'ZAU', 'km' => 1.96],
			['id' => 'ZKOL', 'name' => 'Kollerwiese', 'abbr' => 'ZKOL', 'km' => 3.41],
			['id' => 'NIDO', 'name' => 'Nidelbad Ost', 'abbr' => 'NIDO', 'km' => 9.68],
            ['id' => 'TW', 'name' => 'Thalwil', 'abbr' => 'TW', 'km' => 12.09],
        ]
    ],
    'glattalbahn' => [
        'id' => 'glattalbahn',
        'name' => 'Glattal (ZUE-HI)',
        'stations' => [
            ['id' => 'ZOER', 'name' => 'Oerlikon', 'abbr' => 'ZOER', 'km' => -96.88],
            ['id' => 'WS', 'name' => 'Wallisellen', 'abbr' => 'WS', 'km' => -93.23],
            ['id' => 'CHRI', 'name' => 'Chriesbach', 'abbr' => 'CHRI', 'km' => -91.33],
            ['id' => 'DUE', 'name' => 'Dübendorf', 'abbr' => 'DUE', 'km' => -90.44],
            ['id' => 'SCWE', 'name' => 'Schwerzenbach', 'abbr' => 'SCWE', 'km' => -87.26],
            ['id' => 'NAEN', 'name' => 'Nänikon-Greifensee', 'abbr' => 'NAEN', 'km' => -84.58],
            ['id' => 'UST', 'name' => 'Uster', 'abbr' => 'UST', 'km' => -81.35],
            ['id' => 'AAT', 'name' => 'Aathal', 'abbr' => 'AAT', 'km' => -77.38],
            ['id' => 'WZ', 'name' => 'Wetzikon', 'abbr' => 'WZ', 'km' => -74.51],
            ['id' => 'HI', 'name' => 'Hinwil', 'abbr' => 'HI', 'km' => 70.07],
        ]
    ],
    'züriberg-h' => [
        'id' => 'züriberg-h',
        'name' => 'Züriberg-Hinwil',
        'stations' => [
            ['id' => 'ZAS', 'name' => 'Altstetten', 'abbr' => 'ZAS', 'km' => 95.72],
            ['id' => 'ZHER', 'name' => 'Herdern', 'abbr' => 'ZHER', 'km' => 96.81],
            ['id' => 'ZHDB', 'name' => 'Hardbrücke', 'abbr' => 'ZHDB', 'km' => 97.97],
            ['id' => 'ZMUS', 'name' => 'Museumsstrasse', 'abbr' => 'ZMUS', 'km' => 99.84],
            ['id' => 'ZSTH', 'name' => 'Stadelhofen', 'abbr' => 'ZSTH', 'km' => 101.59],
            ['id' => 'ZHOT', 'name' => 'Hottingen', 'abbr' => 'ZHOT', 'km' => 102.71],
            ['id' => 'STET', 'name' => 'Stettbach', 'abbr' => 'STET', 'km' => 106.94],
            ['id' => 'NGUT', 'name' => 'Neugut', 'abbr' => 'NGUT', 'km' => 108.01],
            ['id' => 'DUE', 'name' => 'Dübendorf', 'abbr' => 'DUE', 'km' => 108.9],
            ['id' => 'SCWE', 'name' => 'Schwerzenbach', 'abbr' => 'SCWE', 'km' => 112.08],
            ['id' => 'NAEN', 'name' => 'Nänikon-Greifensee', 'abbr' => 'NAEN', 'km' => 115.26],
            ['id' => 'UST', 'name' => 'Uster', 'abbr' => 'UST', 'km' => 118.49],
            ['id' => 'AAT', 'name' => 'Aathal', 'abbr' => 'AAT', 'km' => 122.46],
            ['id' => 'WZ', 'name' => 'Wetzikon', 'abbr' => 'WZ', 'km' => 125.33],
            ['id' => 'HI', 'name' => 'Hinwil', 'abbr' => 'HI', 'km' => 129.77],
        ]
    ],
    'züriberg-r' => [
        'id' => 'züriberg-r',
        'name' => 'Altstetten-Rapperswil',
        'stations' => [
            ['id' => 'ZAS', 'name' => 'Altstetten', 'abbr' => 'ZAS', 'km' => 95.72],
            ['id' => 'ZHER', 'name' => 'Herdern', 'abbr' => 'ZHER', 'km' => 96.81],
            ['id' => 'ZHDB', 'name' => 'Hardbrücke', 'abbr' => 'ZHDB', 'km' => 97.97],
            ['id' => 'ZMUS', 'name' => 'Museumsstrasse', 'abbr' => 'ZMUS', 'km' => 99.84],
            ['id' => 'ZSTH', 'name' => 'Stadelhofen', 'abbr' => 'ZSTH', 'km' => 101.59],
            ['id' => 'ZHOT', 'name' => 'Hottingen', 'abbr' => 'ZHOT', 'km' => 102.71],
            ['id' => 'STET', 'name' => 'Stettbach', 'abbr' => 'STET', 'km' => 106.94],
            ['id' => 'NGUT', 'name' => 'Neugut', 'abbr' => 'NGUT', 'km' => 108.01],
            ['id' => 'DUE', 'name' => 'Dübendorf', 'abbr' => 'DUE', 'km' => 108.9],
            ['id' => 'SCWE', 'name' => 'Schwerzenbach', 'abbr' => 'SCWE', 'km' => 112.08],
            ['id' => 'NAEN', 'name' => 'Nänikon-Greifensee', 'abbr' => 'NAEN', 'km' => 115.26],
            ['id' => 'UST', 'name' => 'Uster', 'abbr' => 'UST', 'km' => 118.49],
            ['id' => 'AAT', 'name' => 'Aathal', 'abbr' => 'AAT', 'km' => 122.46],
            ['id' => 'WZ', 'name' => 'Wetzikon', 'abbr' => 'WZ', 'km' => 125.33],
            ['id' => 'BUB', 'name' => 'Bubikon', 'abbr' => 'BUB', 'km' => 131.18],
            ['id' => 'RUE', 'name' => 'Rüti', 'abbr' => 'RUE', 'km' => 133.9],
            ['id' => 'JONA', 'name' => 'Jona', 'abbr' => 'JONA', 'km' => 138.78],
            ['id' => 'RW', 'name' => 'Rapperswil', 'abbr' => 'RW', 'km' => 140.49],
        ]
    ],
    'züriberg-rue' => [
        'id' => 'züriberg-rue',
        'name' => 'Züriberg-Rüti',
        'stations' => [
            ['id' => 'ZMUS', 'name' => 'Museumsstrasse', 'abbr' => 'ZMUS', 'km' => 99.84],
            ['id' => 'ZSTH', 'name' => 'Stadelhofen', 'abbr' => 'ZSTH', 'km' => 101.59],
            ['id' => 'ZHOT', 'name' => 'Hottingen', 'abbr' => 'ZHOT', 'km' => 102.71],
            ['id' => 'STET', 'name' => 'Stettbach', 'abbr' => 'STET', 'km' => 106.94],
            ['id' => 'NGUT', 'name' => 'Neugut', 'abbr' => 'NGUT', 'km' => 108.01],
            ['id' => 'DUE', 'name' => 'Dübendorf', 'abbr' => 'DUE', 'km' => 108.9],
            ['id' => 'SCWE', 'name' => 'Schwerzenbach', 'abbr' => 'SCWE', 'km' => 112.08],
            ['id' => 'NAEN', 'name' => 'Nänikon-Greifensee', 'abbr' => 'NAEN', 'km' => 115.26],
            ['id' => 'UST', 'name' => 'Uster', 'abbr' => 'UST', 'km' => 118.49],
            ['id' => 'AAT', 'name' => 'Aathal', 'abbr' => 'AAT', 'km' => 122.46],
            ['id' => 'WZ', 'name' => 'Wetzikon', 'abbr' => 'WZ', 'km' => 125.33],
            ['id' => 'BUB', 'name' => 'Bubikon', 'abbr' => 'BUB', 'km' => 131.18],
            ['id' => 'RUE', 'name' => 'Rüti', 'abbr' => 'RUE', 'km' => 133.9],
        ]
    ],
    'Kempttalbahn ' => [
        'id' => 'Kempttalbahn ',
        'name' => 'Kempttalbahn ',
        'stations' => [
            ['id' => 'EF', 'name' => 'Effretikon', 'abbr' => 'EF', 'km' => 0],
            ['id' => 'IL', 'name' => 'Ilnau', 'abbr' => 'IL', 'km' => 4.4],
            ['id' => 'FET', 'name' => 'Fehraltdorf', 'abbr' => 'FET', 'km' => 8],
            ['id' => 'PFZ', 'name' => 'Pfäffikon', 'abbr' => 'PFZ', 'km' => 11.3],
            ['id' => 'KN', 'name' => 'Kempten', 'abbr' => 'KN', 'km' => 15.7],
            ['id' => 'WZ', 'name' => 'Wetzikon', 'abbr' => 'WZ', 'km' => 18.1],
            ['id' => 'HI', 'name' => 'Hinwil', 'abbr' => 'HI', 'km' => 22.5],
        ]
    ],
    'nazeli' => [
        'id' => 'nazeli',
        'name' => 'Nationalbahn',
        'stations' => [
            ['id' => 'ZF', 'name' => 'Zofingen', 'abbr' => 'ZF', 'km' => 50.8],
            ['id' => 'KGD', 'name' => 'Küngoldingen', 'abbr' => 'KGD', 'km' => 53.1],
            ['id' => 'WAST', 'name' => 'Walterswil-Striegel', 'abbr' => 'WAST', 'km' => 55.7],
            ['id' => 'SAF', 'name' => 'Safenwil', 'abbr' => 'SAF', 'km' => 57.4],
            ['id' => 'KKO', 'name' => 'Kölliken Oberdorf', 'abbr' => 'KKO', 'km' => 60.1],
            ['id' => 'KK', 'name' => 'Kölliken', 'abbr' => 'KK', 'km' => 61.7],
            ['id' => 'OEF', 'name' => 'Oberentfelden', 'abbr' => 'OEF', 'km' => 64.7],
            ['id' => 'SUHR', 'name' => 'Suhr', 'abbr' => 'SUHR', 'km' => 67.5],
            ['id' => 'HU', 'name' => 'Hunzenschwil', 'abbr' => 'HU', 'km' => 71.0],
            ['id' => 'LB', 'name' => 'Lenzburg', 'abbr' => 'LB', 'km' => 74.5],
            ['id' => 'GEXI', 'name' => 'Gexi', 'abbr' => 'GEXI', 'km' => 76.4],
            ['id' => 'OTH', 'name' => 'Othmarsingen', 'abbr' => 'OTH', 'km' => 78.7],
            ['id' => 'MAEG', 'name' => 'Mägenwil', 'abbr' => 'MAEG', 'km' => 80.5],
            ['id' => 'MEL', 'name' => 'Mellingen', 'abbr' => 'MEL', 'km' => 84.2],
            ['id' => 'DAET', 'name' => 'Dättwil', 'abbr' => 'DAET', 'km' => 86.9],
            ['id' => 'BDO', 'name' => 'Baden Oberstadt', 'abbr' => 'BDO', 'km' => 90.1],
            ['id' => 'WE', 'name' => 'Wettingen', 'abbr' => 'WE', 'km' => 91.6],
        ]
    ],
    'ebikon' => [
        'id' => 'ebikon',
        'name' => 'Ebikon',
        'stations' => [
            ['id' => 'LZ', 'name' => 'Luzern', 'abbr' => 'LZ', 'km' => -66.74],
            ['id' => 'GTS', 'name' => 'Gütsch', 'abbr' => 'GTS', 'km' => -64.04],
            ['id' => 'EBI', 'name' => 'Ebikon', 'abbr' => 'EBI', 'km' => -58.57],
            ['id' => 'BURN', 'name' => 'Buchrain', 'abbr' => 'BURN', 'km' => -57.07],
            ['id' => 'LBD', 'name' => 'Root D4', 'abbr' => 'LBD', 'km' => -55.26],
            ['id' => 'GSK', 'name' => 'Gisikon-Root', 'abbr' => 'GSK', 'km' => -52.82],
            ['id' => 'RK', 'name' => 'Rotkreuz', 'abbr' => 'RK', 'km' => -49],
            ['id' => 'BRGL', 'name' => 'Brüglen', 'abbr' => 'BRGL', 'km' => -46.1],
            ['id' => 'MKR', 'name' => 'Meierskappel-Risch', 'abbr' => 'MKR', 'km' => -45.1],
            ['id' => 'IM', 'name' => 'Immensee', 'abbr' => 'IM', 'km' => -41.8],
            ['id' => 'BRM', 'name' => 'Brunnmatt', 'abbr' => 'BRM', 'km' => -37.77],
            ['id' => 'GD', 'name' => 'Arth-Goldau', 'abbr' => 'GD', 'km' => -33.2],
        ]
    ],
    'verkehrshaus' => [
        'id' => 'verkehrshaus',
        'name' => 'Verkehrshaus am See',
        'stations' => [
            ['id' => 'LZVH', 'name' => 'Verkehrshaus', 'abbr' => 'LZVH', 'km' => 6.1],
            ['id' => 'MEGZ', 'name' => 'Meggen Zentrum', 'abbr' => 'MEGZ', 'km' => 9.5],
            ['id' => 'MEG', 'name' => 'Meggen', 'abbr' => 'MEG', 'km' => 10.7],
            ['id' => 'MERL', 'name' => 'Merlischachen', 'abbr' => 'MERL', 'km' => 13.6],
            ['id' => 'KUE', 'name' => 'Küssnacht', 'abbr' => 'KUE', 'km' => 16.2],
            ['id' => 'IM', 'name' => 'Immensee', 'abbr' => 'IM', 'km' => 19.2],
            ['id' => 'BRM', 'name' => 'Brunnmatt', 'abbr' => 'BRM', 'km' => 23.23],
            ['id' => 'GD', 'name' => 'Arth-Goldau', 'abbr' => 'GD', 'km' => 27.8],
        ]
    ],
    'gottardo-berg-komplett' => [
        'id' => 'gottardo-berg-komplett',
        'name' => 'Gotthard-Berg (GD-GIU)',
        'stations' => [
            ['id' => 'GD', 'name' => 'Arth-Goldau', 'abbr' => 'GD', 'km' => 8.86],
            ['id' => 'SCHW', 'name' => 'Schwyz', 'abbr' => 'SCHW', 'km' => 17.01],
            ['id' => 'BRU', 'name' => 'Brunnen', 'abbr' => 'BRU', 'km' => 20.52],
            ['id' => 'SK', 'name' => 'Sisikon', 'abbr' => 'SK', 'km' => 26.4],
            ['id' => 'GRUO', 'name' => 'Gruonbach', 'abbr' => 'GRUO', 'km' => 30.87],
            ['id' => 'FL', 'name' => 'Flüelen', 'abbr' => 'FL', 'km' => 32.3],
            ['id' => 'AL', 'name' => 'Altdorf', 'abbr' => 'AL', 'km' => 35.25],
            ['id' => 'ER', 'name' => 'Erstfeld', 'abbr' => 'ER', 'km' => 41.58],
            ['id' => 'AS', 'name' => 'Amsteg-Silenen', 'abbr' => 'AS', 'km' => 46.55],
            ['id' => 'ZGRG', 'name' => 'Zgraggen', 'abbr' => 'ZGRG', 'km' => 50.53],
            ['id' => 'GU', 'name' => 'Gurtnellen', 'abbr' => 'GU', 'km' => 54.4],
            ['id' => 'PFAF', 'name' => 'Pfaffensprung', 'abbr' => 'PFAF', 'km' => 58.42],
            ['id' => 'WAS', 'name' => 'Wassen', 'abbr' => 'WAS', 'km' => 62.76],
            ['id' => 'GOE', 'name' => 'Göschenen', 'abbr' => 'GOE', 'km' => 70.45],
            ['id' => 'AI', 'name' => 'Airolo', 'abbr' => 'AI', 'km' => 86.2],
            ['id' => 'AP', 'name' => 'Ambri-Piotta', 'abbr' => 'AP', 'km' => 93.04],
            ['id' => 'RO', 'name' => 'Rodi-Fiesso', 'abbr' => 'RO', 'km' => 97.84],
            ['id' => 'PARD', 'name' => 'Pardorea', 'abbr' => 'PARD', 'km' => 101.93],
            ['id' => 'FA', 'name' => 'Faido', 'abbr' => 'FA', 'km' => 106],
            ['id' => 'BO', 'name' => 'Bodio', 'abbr' => 'BO', 'km' => 125.5],
            ['id' => 'BIA', 'name' => 'Biasca', 'abbr' => 'BIA', 'km' => 131.8],
            ['id' => 'OS', 'name' => 'Osogna-Cresciano', 'abbr' => 'OS', 'km' => 137.96],
            ['id' => 'CLA', 'name' => 'Claro', 'abbr' => 'CLA', 'km' => 143.47],
            ['id' => 'CAST', 'name' => 'Castione-Arbedo', 'abbr' => 'CAST', 'km' => 147.27],
            ['id' => 'SPAO', 'name' => 'San. Paolo', 'abbr' => 'SPAO', 'km' => 149.75],
            ['id' => 'BEL', 'name' => 'Bellinzona', 'abbr' => 'BEL', 'km' => 150.9],
            ['id' => 'GIU', 'name' => 'Giubiasco', 'abbr' => 'GIU', 'km' => 154.04],
        ]
    ],
    // FIX: War vorher ebenfalls 'gottardo-berg-komplett' — Key korrigiert zu 'gottardo-berg-sud'
    'gottardo-berg-sud' => [
        'id' => 'gottardo-berg-sud',
        'name' => 'Gotthard-Berg-Süd (FL-CAST)',
        'stations' => [
            ['id' => 'FL', 'name' => 'Flüelen', 'abbr' => 'FL', 'km' => 32.3],
            ['id' => 'AL', 'name' => 'Altdorf', 'abbr' => 'AL', 'km' => 35.25],
            ['id' => 'ER', 'name' => 'Erstfeld', 'abbr' => 'ER', 'km' => 41.58],
            ['id' => 'AS', 'name' => 'Amsteg-Silenen', 'abbr' => 'AS', 'km' => 46.55],
            ['id' => 'ZGRG', 'name' => 'Zgraggen', 'abbr' => 'ZGRG', 'km' => 50.53],
            ['id' => 'GU', 'name' => 'Gurtnellen', 'abbr' => 'GU', 'km' => 54.4],
            ['id' => 'PFAF', 'name' => 'Pfaffensprung', 'abbr' => 'PFAF', 'km' => 58.42],
            ['id' => 'WAS', 'name' => 'Wassen', 'abbr' => 'WAS', 'km' => 62.76],
            ['id' => 'GOE', 'name' => 'Göschenen', 'abbr' => 'GOE', 'km' => 70.45],
            ['id' => 'AI', 'name' => 'Airolo', 'abbr' => 'AI', 'km' => 86.2],
            ['id' => 'AP', 'name' => 'Ambri-Piotta', 'abbr' => 'AP', 'km' => 93.04],
            ['id' => 'RO', 'name' => 'Rodi-Fiesso', 'abbr' => 'RO', 'km' => 97.84],
            ['id' => 'PARD', 'name' => 'Pardorea', 'abbr' => 'PARD', 'km' => 101.93],
            ['id' => 'FA', 'name' => 'Faido', 'abbr' => 'FA', 'km' => 106],
            ['id' => 'BO', 'name' => 'Bodio', 'abbr' => 'BO', 'km' => 125.5],
            ['id' => 'BIA', 'name' => 'Biasca', 'abbr' => 'BIA', 'km' => 131.8],
        ]
    ],
    'gäu' => [
        'id' => 'gäu',
        'name' => 'Gäu',
        'stations' => [
            ['id' => 'SO', 'name' => 'Solothurn', 'abbr' => 'SO', 'km' => -73.8],
            ['id' => 'LUT', 'name' => 'Lutbach-Attisholz', 'abbr' => 'LUT', 'km' => -70.4],
            ['id' => 'DN', 'name' => 'Deitingen', 'abbr' => 'DN', 'km' => -67.6],
            ['id' => 'WAA', 'name' => 'Wangen an der Aare', 'abbr' => 'WAA', 'km' => -64.3],
            ['id' => 'NB', 'name' => 'Niederipp', 'abbr' => 'NB', 'km' => -58.6],
            ['id' => 'OEN', 'name' => 'Oensingen', 'abbr' => 'OEN', 'km' => -56.6],
            ['id' => 'OB', 'name' => 'Oberbuchsiten', 'abbr' => 'OB', 'km' => -51.4],
            ['id' => 'EG', 'name' => 'Egerkingen', 'abbr' => 'EG', 'km' => -49.1],
            ['id' => 'HRK', 'name' => 'Härkingen Post', 'abbr' => 'HRK', 'km' => -47],
            ['id' => 'HAE', 'name' => 'Hägendorf', 'abbr' => 'HAE', 'km' => -45.3],
            ['id' => 'WBO', 'name' => 'Wangen b.O.', 'abbr' => 'WBO', 'km' => -43],
            ['id' => 'OLH', 'name' => 'Hammer', 'abbr' => 'OLH', 'km' => -40.6],
        ]
    ],
    'abs' => [
        'id' => 'abs',
        'name' => '450 ABS',
        'stations' => [
            ['id' => 'SO', 'name' => 'Solothurn', 'abbr' => 'SO', 'km' => -79.4],
            ['id' => 'SCIN', 'name' => 'Scintilla', 'abbr' => 'SCIN', 'km' => -79],
            ['id' => 'DER', 'name' => 'Derendingen', 'abbr' => 'DER', 'km' => -77.2],
            ['id' => 'SBN', 'name' => 'Subingen', 'abbr' => 'SBN', 'km' => -74.8],
            ['id' => 'ETZ', 'name' => 'Etziken', 'abbr' => 'ETZ', 'km' => -72.8],
            ['id' => 'INKV', 'name' => 'Inkwil', 'abbr' => 'INKV', 'km' => -70.3],
            ['id' => 'WANZ', 'name' => 'Wanzwil', 'abbr' => 'WANZ', 'km' => -68.5],
            ['id' => 'LTHL', 'name' => 'Langenthaltunnel', 'abbr' => 'LTHL', 'km' => -61.6],
            ['id' => 'MUBR', 'name' => 'Murgenthal Brunnmatten', 'abbr' => 'MUBR', 'km' => -55.9],
            ['id' => 'RTRW', 'name' => 'Rothrist West', 'abbr' => 'RTRW', 'km' => -49.3],
			['id' => 'RTR', 'name' => 'Rothrist', 'abbr' => 'RTR', 'km' => -48.1],
        ]
    ],
    'nbs' => [
        'id' => '400',
        'name' => '400 NBS',
        'stations' => [
            ['id' => 'LGUT', 'name' => 'Löchligut', 'abbr' => 'LGUT', 'km' => 4.9],
            ['id' => 'MATA', 'name' => 'Aespli', 'abbr' => 'MATA', 'km' => 12.3],
            ['id' => 'HERS', 'name' => 'Hersiwil', 'abbr' => 'HERS', 'km' => 30.1],
            ['id' => 'OENT', 'name' => 'Oenzberg', 'abbr' => 'OENT', 'km' => 33.1],
            ['id' => 'WANZ', 'name' => 'Wanzwil', 'abbr' => 'WANZ', 'km' => 36],
            ['id' => 'LTHL', 'name' => 'Langenthaltunnel', 'abbr' => 'LTHL', 'km' => 42.9],
            ['id' => 'MUBR', 'name' => 'Murgenthal Brunnmatten', 'abbr' => 'MUBR', 'km' => 48.6],
            ['id' => 'RTRW', 'name' => 'Rothrist West', 'abbr' => 'RTRW', 'km' => 55.2],
			['id' => 'RTR', 'name' => 'Rothrist', 'abbr' => 'RTR', 'km' => 56.4],
        ]
    ],
    'stammstrecke-abo' => [
        'id' => 'stammstrecke-abo',
        'name' => 'LGUT-BDF-ABO',
        'stations' => [
            ['id' => 'BNWD/WKD', 'name' => 'BNWD/WKD', 'abbr' => 'BNWD/WKD', 'km' => -102.95],
            ['id' => 'LGUT', 'name' => 'Löchligut', 'abbr' => 'LGUT', 'km' => -101.28],
            ['id' => 'ZOL', 'name' => 'Zollikofen', 'abbr' => 'ZOL', 'km' => -98.81],
            ['id' => 'SCHB', 'name' => 'Schönbühl', 'abbr' => 'SCHB', 'km' => -94.91],
            ['id' => 'MAT', 'name' => 'Mattstetten', 'abbr' => 'MAT', 'km' => -93.15],
            ['id' => 'MATA', 'name' => 'MATA', 'abbr' => 'MATA', 'km' => -91.98],
            ['id' => 'HRDF', 'name' => 'Hardfeld', 'abbr' => 'HRDF', 'km' => -91.66],
            ['id' => 'HBK', 'name' => 'Hindelbank', 'abbr' => 'HBK', 'km' => -89.73],
            ['id' => 'SAAC', 'name' => 'Sandacher', 'abbr' => 'SAAC', 'km' => -87.2],
            ['id' => 'LYS', 'name' => 'Lyssach', 'abbr' => 'LYS', 'km' => -86.54],
            ['id' => 'BDF', 'name' => 'Burgdorf', 'abbr' => 'BDF', 'km' => -83.39],
            ['id' => 'WY', 'name' => 'Wynigen', 'abbr' => 'WY', 'km' => -76.93],
            ['id' => 'RTW', 'name' => 'Riedtwil', 'abbr' => 'RTW', 'km' => -72.33],
            ['id' => 'HB', 'name' => 'Herzogenbuchsee', 'abbr' => 'HB', 'km' => -66.8],
            ['id' => 'LTG', 'name' => 'Langenthal GB', 'abbr' => 'LTG', 'km' => -61.1],
            ['id' => 'LTH', 'name' => 'Langenthal', 'abbr' => 'LTH', 'km' => -59.2],
            ['id' => 'ROG', 'name' => 'Roggwil-Wynau', 'abbr' => 'ROG', 'km' => -54.49],
            ['id' => 'MGT', 'name' => 'Murgenthal', 'abbr' => 'MGT', 'km' => -52.22],
            ['id' => 'RANS', 'name' => 'RANS', 'abbr' => 'RANS', 'km' => -49.07],
            ['id' => 'RTRH', 'name' => 'Hungerzelg', 'abbr' => 'RTRH', 'km' => -48.5],
            ['id' => 'RTRW', 'name' => 'Rothrist West', 'abbr' => 'RTRW', 'km' => -47.35],
            ['id' => 'RTR', 'name' => 'Rothrist', 'abbr' => 'RTR', 'km' => -46.2],
            ['id' => 'BFG', 'name' => 'Bifang', 'abbr' => 'BFG', 'km' => -44.86],
            ['id' => 'ABOW', 'name' => 'ABOW', 'abbr' => 'ABOW', 'km' => -43.97],
            ['id' => 'ABO', 'name' => 'Aarburg-Oftringen', 'abbr' => 'ABO', 'km' => -43.01],
            ['id' => 'OL', 'name' => 'Olten', 'abbr' => 'OL', 'km' => -39.29],
        ]
    ],
    'langenthal' => [
        'id' => 'langenthal',
        'name' => 'BDF-MGT',
        'stations' => [
            ['id' => 'BDF', 'name' => 'Burgdorf', 'abbr' => 'BDF', 'km' => -83.39],
            ['id' => 'WY', 'name' => 'Wynigen', 'abbr' => 'WY', 'km' => -76.93],
            ['id' => 'RTW', 'name' => 'Riedtwil', 'abbr' => 'RTW', 'km' => -72.33],
            ['id' => 'HB', 'name' => 'Herzogenbuchsee', 'abbr' => 'HB', 'km' => -66.8],
            ['id' => 'LTG', 'name' => 'Langenthal GB', 'abbr' => 'LTG', 'km' => -61.1],
            ['id' => 'LTH', 'name' => 'Langenthal', 'abbr' => 'LTH', 'km' => -59.2],
            ['id' => 'ROG', 'name' => 'Roggwil-Wynau', 'abbr' => 'ROG', 'km' => -54.49],
            ['id' => 'MGT', 'name' => 'Murgenthal', 'abbr' => 'MGT', 'km' => -52.22],
        ]
    ],
    'stammstrecke' => [
        'id' => 'stammstrecke',
        'name' => 'LGUT-BDF-RTW',
        'stations' => [
            ['id' => 'BNWD/WKD', 'name' => 'BNWD/WKD', 'abbr' => 'BNWD/WKD', 'km' => -102.95],
            ['id' => 'LGUT', 'name' => 'Löchligut', 'abbr' => 'LGUT', 'km' => -101.28],
            ['id' => 'ZOL', 'name' => 'Zollikofen', 'abbr' => 'ZOL', 'km' => -98.81],
            ['id' => 'SCHB', 'name' => 'Schönbühl', 'abbr' => 'SCHB', 'km' => -94.91],
            ['id' => 'MAT', 'name' => 'Mattstetten', 'abbr' => 'MAT', 'km' => -93.15],
            ['id' => 'MATA', 'name' => 'MATA', 'abbr' => 'MATA', 'km' => -91.98],
            ['id' => 'HRDF', 'name' => 'Hardfeld', 'abbr' => 'HRDF', 'km' => -91.66],
            ['id' => 'HBK', 'name' => 'Hindelbank', 'abbr' => 'HBK', 'km' => -89.73],
            ['id' => 'SAAC', 'name' => 'Sandacher', 'abbr' => 'SAAC', 'km' => -87.2],
            ['id' => 'LYS', 'name' => 'Lyssach', 'abbr' => 'LYS', 'km' => -86.54],
            ['id' => 'BDF', 'name' => 'Burgdorf', 'abbr' => 'BDF', 'km' => -83.39],
            ['id' => 'WY', 'name' => 'Wynigen', 'abbr' => 'WY', 'km' => -76.93],
            ['id' => 'RTW', 'name' => 'Riedtwil', 'abbr' => 'RTW', 'km' => -72.33],
        ]
    ],
    'gürbetal' => [
        'id' => '303',
        'name' => '303 - Gürbetal',
        'stations' => [
            ['id' => 'HOL', 'name' => 'Holligen', 'abbr' => 'HOL', 'km' => 2.71],
			['id' => 'BNAH', 'name' => 'Ausserholligen GBS', 'abbr' => 'BNAH', 'km' => 3.12],
			['id' => 'BNFI', 'name' => 'Bern Fischermätteli', 'abbr' => 'BNFI', 'km' => 3.52],
            ['id' => 'BNWE', 'name' => 'Bern Weissenbühl', 'abbr' => 'BNWE', 'km' => 5.09],
            ['id' => 'WBB', 'name' => 'Wabern b. Bern', 'abbr' => 'WBB', 'km' => 6.57],
            ['id' => 'KSN', 'name' => 'Kehrsatz Nord', 'abbr' => 'KSN', 'km' => 8.77],
            ['id' => 'KS', 'name' => 'Kehrsatz', 'abbr' => 'KS', 'km' => 9.67],
            ['id' => 'BPST', 'name' => 'Belp Steinbach', 'abbr' => 'BPST', 'km' => 11.92],
            ['id' => 'BP', 'name' => 'Belp', 'abbr' => 'BP', 'km' => 12.7],
            ['id' => 'TO', 'name' => 'Toffen', 'abbr' => 'TO', 'km' => 16.13],
            ['id' => 'KD', 'name' => 'Kaufdorf', 'abbr' => 'KD', 'km' => 18.47],
            ['id' => 'THU', 'name' => 'Thurnen', 'abbr' => 'THU', 'km' => 21.34],
            ['id' => 'BWA', 'name' => 'Burgistein', 'abbr' => 'BWA', 'km' => 24.2],
            ['id' => 'SF', 'name' => 'Seftigen', 'abbr' => 'SF', 'km' => 25.72],
            ['id' => 'UE', 'name' => 'Uetendorf', 'abbr' => 'UE', 'km' => 29.3],
            ['id' => 'UEA', 'name' => 'Uetendorf Allmend', 'abbr' => 'UEA', 'km' => 30.99],
            ['id' => 'LNF', 'name' => 'Lerchenfeld', 'abbr' => 'LNF', 'km' => 32.08],
            ['id' => 'TH', 'name' => 'Thun', 'abbr' => 'TH', 'km' => 34.47],
        ]
    ],
    'aaretal' => [
        'id' => '290',
        'name' => '301 - Aaretal',
        'stations' => [
            ['id' => 'BN', 'name' => 'Bern', 'abbr' => 'BN', 'km' => 106.13],
            ['id' => 'BNWD', 'name' => 'Bern Wankdorf', 'abbr' => 'BNWD', 'km' => 108.98],
            ['id' => 'OST', 'name' => 'Ostermundigen', 'abbr' => 'OST', 'km' => 110.77],
            ['id' => 'GUE', 'name' => 'Gümligen', 'abbr' => 'GUE', 'km' => 113.96],
            ['id' => 'RUB', 'name' => 'Rubigen', 'abbr' => 'RUB', 'km' => 119.04],
            ['id' => 'MS', 'name' => 'Münsingen', 'abbr' => 'MS', 'km' => 122.13],
            ['id' => 'WCH', 'name' => 'Wichtrach', 'abbr' => 'WCH', 'km' => 125.73],
            ['id' => 'KI', 'name' => 'Kiesen', 'abbr' => 'KI', 'km' => 128.3],
            ['id' => 'UTI', 'name' => 'Uttigen', 'abbr' => 'UTI', 'km' => 131.1],
            ['id' => 'LNF', 'name' => 'Lerchenfeld', 'abbr' => 'LNF', 'km' => 134.10],
            ['id' => 'TH', 'name' => 'Thun', 'abbr' => 'TH', 'km' => 137.02],
        ]
    ],
    'seeland-ost' => [
        'id' => 'seeland-ost',
        'name' => '260 - Seeland Ost',
        'stations' => [
            ['id' => 'BN', 'name' => 'Bern', 'abbr' => 'BN', 'km' => 0.1],
            ['id' => 'BNWD', 'name' => 'Wankdorf', 'abbr' => 'BNWD', 'km' => 3.3],
            ['id' => 'ZOL', 'name' => 'Zollikofen', 'abbr' => 'ZOL', 'km' => 7.46],
            ['id' => 'MUEB', 'name' => 'Münchenbuchsee', 'abbr' => 'MUEB', 'km' => 10.12],
            ['id' => 'SCUE', 'name' => 'Schüpfen', 'abbr' => 'SCUE', 'km' => 15.69],
            ['id' => 'SUB', 'name' => 'Suberg-Grossaffoltern', 'abbr' => 'SUB', 'km' => 19.92],
            ['id' => 'LY', 'name' => 'Lyss', 'abbr' => 'LY', 'km' => 22.5],
            ['id' => 'BUS', 'name' => 'Busswil', 'abbr' => 'BUS', 'km' => 26.16],
            ['id' => 'STU', 'name' => 'Studen', 'abbr' => 'STU', 'km' => 28.12],
            ['id' => 'DON', 'name' => 'Dotzigen', 'abbr' => 'DON', 'km' => 28.89],
            ['id' => 'BGG', 'name' => 'Brügg', 'abbr' => 'BGG', 'km' => 30.51],
            ['id' => 'BUER', 'name' => 'Büren a.d.A.', 'abbr' => 'BUER', 'km' => 32.31],
            ['id' => 'BI', 'name' => 'Biel/Bienne', 'abbr' => 'BI', 'km' => 33.6],
        ]
    ],
    'sempachersee' => [
        'id' => 'sempachersee',
        'name' => 'Sempachersee',
        'stations' => [
            ['id' => 'ZF', 'name' => 'Zofingen', 'abbr' => 'ZF', 'km' => 47.46],
            ['id' => 'BRIT', 'name' => 'Brittnau-Wikon', 'abbr' => 'BRIT', 'km' => 50.48],
            ['id' => 'REID', 'name' => 'Reiden', 'abbr' => 'REID', 'km' => 52.99],
            ['id' => 'DAG', 'name' => 'Dagmerseeln', 'abbr' => 'DAG', 'km' => 55.8],
            ['id' => 'NEB', 'name' => 'Nebikon', 'abbr' => 'NEB', 'km' => 58.74],
            ['id' => 'WAU', 'name' => 'Wauwail', 'abbr' => 'WAU', 'km' => 62.52],
            ['id' => 'STER', 'name' => 'St. Erhard-Knutwil', 'abbr' => 'STER', 'km' => 66.8],
            ['id' => 'SS', 'name' => 'Sursee', 'abbr' => 'SS', 'km' => 69.4],
            ['id' => 'OBK', 'name' => 'Oberkirch', 'abbr' => 'OBK', 'km' => 71.17],
            ['id' => 'NO', 'name' => 'Nottwil', 'abbr' => 'NO', 'km' => 73.78],
            ['id' => 'SEM', 'name' => 'Sempach-Neuenkirch', 'abbr' => 'SEM', 'km' => 78.99],
            ['id' => 'RBG', 'name' => 'Rothenburg', 'abbr' => 'RBG', 'km' => 84.55],
            ['id' => 'RBGD', 'name' => 'Kapf', 'abbr' => 'RBGD', 'km' => 87],
            ['id' => 'GSAG', 'name' => 'Gersag', 'abbr' => 'GSAG', 'km' => 89.16],
            ['id' => 'EBR', 'name' => 'Emmenbrücke', 'abbr' => 'EBR', 'km' => 90.19],
            ['id' => 'GTS', 'name' => 'Gütsch', 'abbr' => 'GTS', 'km' => 92.85],
        ]
    ],
    'doubs' => [
        'id' => 'doubs',
        'name' => 'Doubs',
        'stations' => [
            ['id' => 'BN', 'name' => 'BN', 'abbr' => 'BN', 'km' => 405.7],
            ['id' => 'BN2', 'name' => 'BN2', 'abbr' => 'BN2', 'km' => 406.1],
            ['id' => 'BN bif', 'name' => 'BN bif', 'abbr' => 'BN bif', 'km' => 407.1],
            ['id' => 'RBE', 'name' => 'RBE', 'abbr' => 'RBE', 'km' => 414.5],
            ['id' => 'NOV', 'name' => 'NOV', 'abbr' => 'NOV', 'km' => 416.4],
            ['id' => 'DLZ', 'name' => 'DLZ', 'abbr' => 'DLZ', 'km' => 421.7],
            ['id' => 'LJY', 'name' => 'LJY', 'abbr' => 'LJY', 'km' => 423.5],
            ['id' => 'DOU', 'name' => 'DOU', 'abbr' => 'DOU', 'km' => 428],
            ['id' => 'BDA', 'name' => 'BDA', 'abbr' => 'BDA', 'km' => 437.9],
            ['id' => 'HYP', 'name' => 'HYP', 'abbr' => 'HYP', 'km' => 444.8],
            ['id' => 'CVL', 'name' => 'CVL', 'abbr' => 'CVL', 'km' => 453.5],
            ['id' => 'CVLbis', 'name' => 'CVLbis', 'abbr' => 'CVLbis', 'km' => 454],
            ['id' => 'POM', 'name' => 'POM', 'abbr' => 'POM', 'km' => 456.96],
            ['id' => 'RAN', 'name' => 'RAN', 'abbr' => 'RAN', 'km' => 460.6],
            ['id' => 'ISD', 'name' => 'ISD', 'abbr' => 'ISD', 'km' => 463.3],
            ['id' => 'SMD', 'name' => 'SMD', 'abbr' => 'SMD', 'km' => 468.9],
            ['id' => 'CFT', 'name' => 'CFT', 'abbr' => 'CFT', 'km' => 472.2],
            ['id' => 'VJT', 'name' => 'VJT', 'abbr' => 'VJT', 'km' => 478.8],
            ['id' => 'MBD', 'name' => 'MBD', 'abbr' => 'MBD', 'km' => 483.9],
        ]
    ],
    'montbeliard-doubs' => [
        'id' => 'montbeliard-doubs',
        'name' => 'Montbéliard (Doubs)',
        'stations' => [
            ['id' => 'VJT', 'name' => 'VJT', 'abbr' => 'VJT', 'km' => 478.8],
            ['id' => 'bif AUD', 'name' => 'bif AUD', 'abbr' => 'bif AUD', 'km' => 482.2],
            ['id' => 'MBD', 'name' => 'MBD', 'abbr' => 'MBD', 'km' => 483.9],
            ['id' => 'MBDx', 'name' => 'MBDx', 'abbr' => 'MBDx', 'km' => 485],
            ['id' => 'MBDy', 'name' => 'MBDy', 'abbr' => 'MBDy', 'km' => 485.5],
            ['id' => 'HCT', 'name' => 'HCT', 'abbr' => 'HCT', 'km' => 491.7],
            ['id' => 'BFTS', 'name' => 'BFTS', 'abbr' => 'BFTS', 'km' => 499.8],
            ['id' => 'BFT', 'name' => 'BFT', 'abbr' => 'BFT', 'km' => 501.5],
            ['id' => 'CMF', 'name' => 'CMF', 'abbr' => 'CMF', 'km' => 507.3],
            ['id' => 'PZC', 'name' => 'PZC', 'abbr' => 'PZC', 'km' => 513.1],
            ['id' => 'MVX', 'name' => 'MVX', 'abbr' => 'MVX', 'km' => 515.6],
            ['id' => 'VDX', 'name' => 'VDX', 'abbr' => 'VDX', 'km' => 518.4],
            ['id' => 'DAN', 'name' => 'DAN', 'abbr' => 'DAN', 'km' => 523.8],
            ['id' => 'BLF', 'name' => 'BLF', 'abbr' => 'BLF', 'km' => 526.4],
            ['id' => 'ALK', 'name' => 'ALK', 'abbr' => 'ALK', 'km' => 533.1],
            ['id' => 'WHM', 'name' => 'WHM', 'abbr' => 'WHM', 'km' => 536.2],
            ['id' => 'TGH', 'name' => 'TGH', 'abbr' => 'TGH', 'km' => 537.7],
            ['id' => 'IFH', 'name' => 'IFH', 'abbr' => 'IFH', 'km' => 540.8],
            ['id' => 'ZIL', 'name' => 'ZIL', 'abbr' => 'ZIL', 'km' => 543.7],
            ['id' => 'FXL', 'name' => 'FXL', 'abbr' => 'FXL', 'km' => 544.7],
            ['id' => 'BPW', 'name' => 'BPW', 'abbr' => 'BPW', 'km' => 547.2],
            ['id' => 'HNR', 'name' => 'HNR', 'abbr' => 'HNR', 'km' => 549.32],
            ['id' => 'MSE', 'name' => 'MSE', 'abbr' => 'MSE', 'km' => 550.6],
        ]
    ],
    'unterbruch' => [
        'id' => '999',
        'name' => '< ----------------------------------------- >',
        'stations' => [
            ['id' => 'A', 'name' => 'Aadorf', 'abbr' => 'AAA', 'km' => 0],
            ['id' => 'B', 'name' => 'Bethal', 'abbr' => 'BBB', 'km' => 10],
        ]
    ],

];

// =========================================================================
// AUTOMATISCHE GENERIERUNG VON GEGENBAHN-ROUTEN
// =========================================================================
$routes_to_reverse = [];
foreach ($ROUTES as $id => $route) {
    // Doppelten Code bereinigt
    if (strpos($id, '-inv') === false) {
        $routes_to_reverse[$id] = $route;
    }
}

foreach ($routes_to_reverse as $id => $route) {
    $reversed_id = $id . '-inv';
    $reversed_stations = array_reverse($route['stations']);
    $max_km = max(array_column($route['stations'], 'km'));
    
    foreach ($reversed_stations as &$station) {
        // Subtraktion durchführen und auf maximal 3 Nachkommastellen runden
        $station['km'] = round($max_km - $station['km'], 3);
    }
    unset($station);
    
    $ROUTES[$reversed_id] = [
        'id' => $reversed_id,
        'name' => $route['name'] . ' (inverted)',
        'stations' => $reversed_stations
    ];
}
